//------------------------------------------------------------------------------
// <auto-generated>
//     Deze code is gegenereerd met een hulpprogramma.
//     Runtime-versie:2.0.50727.5485
//
//     Als u wijzigingen aanbrengt in dit bestand, kan dit onjuist gedrag veroorzaken wanneer
//     de code wordt gegenereerd.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace RabbitMetaQueue.Schema {
    using System.Xml.Serialization;
    
    
    /// <opmerkingen/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schema.x2software.net/RabbitMetaQueue")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schema.x2software.net/RabbitMetaQueue", IsNullable=false)]
    public partial class Topology {
        
        private Exchange[] exchangesField;
        
        private Queue[] queuesField;
        
        /// <opmerkingen/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Exchange[] Exchanges {
            get {
                return this.exchangesField;
            }
            set {
                this.exchangesField = value;
            }
        }
        
        /// <opmerkingen/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Queue[] Queues {
            get {
                return this.queuesField;
            }
            set {
                this.queuesField = value;
            }
        }
    }
    
    /// <opmerkingen/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.x2software.net/RabbitMetaQueue")]
    public partial class Exchange {
        
        private Argument[] argumentsField;
        
        private string nameField;
        
        private ExchangeType typeField;
        
        private bool durableField;
        
        public Exchange() {
            this.durableField = true;
        }
        
        /// <opmerkingen/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Argument[] Arguments {
            get {
                return this.argumentsField;
            }
            set {
                this.argumentsField = value;
            }
        }
        
        /// <opmerkingen/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <opmerkingen/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ExchangeType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <opmerkingen/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool durable {
            get {
                return this.durableField;
            }
            set {
                this.durableField = value;
            }
        }
    }
    
    /// <opmerkingen/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.x2software.net/RabbitMetaQueue")]
    public partial class Argument {
        
        private string nameField;
        
        private string valueField;
        
        /// <opmerkingen/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <opmerkingen/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <opmerkingen/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.x2software.net/RabbitMetaQueue")]
    public partial class Binding {
        
        private Argument[] argumentsField;
        
        private string exchangeField;
        
        private string routingKeyField;
        
        /// <opmerkingen/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Argument[] Arguments {
            get {
                return this.argumentsField;
            }
            set {
                this.argumentsField = value;
            }
        }
        
        /// <opmerkingen/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string exchange {
            get {
                return this.exchangeField;
            }
            set {
                this.exchangeField = value;
            }
        }
        
        /// <opmerkingen/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string routingKey {
            get {
                return this.routingKeyField;
            }
            set {
                this.routingKeyField = value;
            }
        }
    }
    
    /// <opmerkingen/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.x2software.net/RabbitMetaQueue")]
    public partial class Queue {
        
        private Argument[] argumentsField;
        
        private Binding[] bindingsField;
        
        private string nameField;
        
        private bool durableField;
        
        public Queue() {
            this.durableField = true;
        }
        
        /// <opmerkingen/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Argument[] Arguments {
            get {
                return this.argumentsField;
            }
            set {
                this.argumentsField = value;
            }
        }
        
        /// <opmerkingen/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Binding[] Bindings {
            get {
                return this.bindingsField;
            }
            set {
                this.bindingsField = value;
            }
        }
        
        /// <opmerkingen/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <opmerkingen/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool durable {
            get {
                return this.durableField;
            }
            set {
                this.durableField = value;
            }
        }
    }
    
    /// <opmerkingen/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.x2software.net/RabbitMetaQueue")]
    public enum ExchangeType {
        
        /// <opmerkingen/>
        Fanout,
        
        /// <opmerkingen/>
        Direct,
        
        /// <opmerkingen/>
        Topic,
        
        /// <opmerkingen/>
        Headers,
    }
}
